version: 2
jobs:
  build:
    docker: # See https://docs.docker.com/get-started/#docker-concepts if you are new to Docker.
      - image: vkravets/jftn-build:java1.8_thrift0.12
    environment:
      - LANG: ru_RU.UTF-8
    steps:
      - checkout
      - run:
          name: Build & Tests
          command: |
            ./gradlew build -x test
            ./gradlew test
