/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.fidonet.jftn.rpc;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum Response implements org.apache.thrift.TEnum {
  OK(0),
  ERROR(1),
  SESSION_OLD(2),
  AUTHORIZATION_FAILED(3);

  private final int value;

  Response(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static Response findByValue(int value) { 
    switch (value) {
      case 0:
        return OK;
      case 1:
        return ERROR;
      case 2:
        return SESSION_OLD;
      case 3:
        return AUTHORIZATION_FAILED;
      default:
        return null;
    }
  }
}
